services:
  college-api:
    build: .
    container_name: student_portal
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_CLUSTER}.mongodb.net/${MONGODB_DB}?retryWrites=true&w=majority