spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/student_portal}


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    url: /openapi.yml

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG


server:
  port: 8080
